package:
  name: satlas
  version: "0.1.0b16"

source:
  fn: master.zip
  url: https://github.com/woutergins/satlas/archive/master.zip
  # md5:
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - satlas = satlas:main
    #
    # Would create an entry point called satlas that calls satlas.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - sympy
    - matplotlib
    - pandas
    - emcee
    - lmfit ==0.8.2
    - tqdm
    - h5py

  run:
    - python
    - numpy
    - scipy
    - sympy
    - matplotlib
    - pandas
    - emcee
    - lmfit ==0.8.2
    - tqdm
    - h5py

test:
  # Python imports
  imports:
    - satlas

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://woutergins.github.io/satlas/
  license: MIT License
  summary: 'This Python package has been created with the goal of creating an easier interface for the analysis of data gathered from laser spectroscopy experiments. Support for fitting the spectra, using both chi2-fitting and Maximum Likelihood Estimation routines, are present.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
